package errors

import "net/http"

// Base error codes from better-auth `packages/core/src/error/codes.ts`, registered so Lookup/Codes see them.
// Messages must match the TypeScript source exactly; statuses are the most common ones used upstream.
var (
	ErrUserNotFound                         = Err(http.StatusNotFound, "USER_NOT_FOUND", "User not found")
	ErrFailedToCreateUser                   = Err(http.StatusUnprocessableEntity, "FAILED_TO_CREATE_USER", "Failed to create user")
	ErrFailedToCreateSession                = Err(http.StatusInternalServerError, "FAILED_TO_CREATE_SESSION", "Failed to create session")
	ErrFailedToUpdateUser                   = Err(http.StatusInternalServerError, "FAILED_TO_UPDATE_USER", "Failed to update user")
	ErrFailedToGetSession                   = Err(http.StatusInternalServerError, "FAILED_TO_GET_SESSION", "Failed to get session")
	ErrInvalidPassword                      = Err(http.StatusBadRequest, "INVALID_PASSWORD", "Invalid password")
	ErrInvalidEmail                         = Err(http.StatusBadRequest, "INVALID_EMAIL", "Invalid email")
	ErrInvalidEmailOrPassword               = Err(http.StatusUnauthorized, "INVALID_EMAIL_OR_PASSWORD", "Invalid email or password")
	ErrInvalidUser                          = Err(http.StatusBadRequest, "INVALID_USER", "Invalid user")
	ErrSocialAccountAlreadyLinked           = Err(http.StatusBadRequest, "SOCIAL_ACCOUNT_ALREADY_LINKED", "Social account already linked")
	ErrProviderNotFound                     = Err(http.StatusNotFound, "PROVIDER_NOT_FOUND", "Provider not found")
	ErrInvalidToken                         = Err(http.StatusBadRequest, "INVALID_TOKEN", "Invalid token")
	ErrTokenExpired                         = Err(http.StatusUnauthorized, "TOKEN_EXPIRED", "Token expired")
	ErrIDTokenNotSupported                  = Err(http.StatusNotFound, "ID_TOKEN_NOT_SUPPORTED", "id_token not supported")
	ErrFailedToGetUserInfo                  = Err(http.StatusUnauthorized, "FAILED_TO_GET_USER_INFO", "Failed to get user info")
	ErrUserEmailNotFound                    = Err(http.StatusUnauthorized, "USER_EMAIL_NOT_FOUND", "User email not found")
	ErrEmailNotVerified                     = Err(http.StatusForbidden, "EMAIL_NOT_VERIFIED", "Email not verified")
	ErrPasswordTooShort                     = Err(http.StatusBadRequest, "PASSWORD_TOO_SHORT", "Password too short")
	ErrPasswordTooLong                      = Err(http.StatusBadRequest, "PASSWORD_TOO_LONG", "Password too long")
	ErrUserAlreadyExists                    = Err(http.StatusUnprocessableEntity, "USER_ALREADY_EXISTS", "User already exists.")
	ErrUserAlreadyExistsUseAnotherEmail     = Err(http.StatusUnprocessableEntity, "USER_ALREADY_EXISTS_USE_ANOTHER_EMAIL", "User already exists. Use another email.")
	ErrEmailCanNotBeUpdated                 = Err(http.StatusBadRequest, "EMAIL_CAN_NOT_BE_UPDATED", "Email can not be updated")
	ErrChangeEmailDisabled                  = Err(http.StatusBadRequest, "CHANGE_EMAIL_DISABLED", "Change email is disabled")
	ErrCredentialAccountNotFound            = Err(http.StatusBadRequest, "CREDENTIAL_ACCOUNT_NOT_FOUND", "Credential account not found")
	ErrSessionExpired                       = Err(http.StatusBadRequest, "SESSION_EXPIRED", "Session expired. Re-authenticate to perform this action.")
	ErrFailedToUnlinkLastAccount            = Err(http.StatusBadRequest, "FAILED_TO_UNLINK_LAST_ACCOUNT", "You can't unlink your last account")
	ErrAccountNotFound                      = Err(http.StatusBadRequest, "ACCOUNT_NOT_FOUND", "Account not found")
	ErrUserAlreadyHasPassword               = Err(http.StatusBadRequest, "USER_ALREADY_HAS_PASSWORD", "User already has a password. Provide that to delete the account.")
	ErrCrossSiteNavigationLoginBlocked      = Err(http.StatusForbidden, "CROSS_SITE_NAVIGATION_LOGIN_BLOCKED", "Cross-site navigation login blocked. This request appears to be a CSRF attack.")
	ErrVerificationEmailNotEnabled          = Err(http.StatusBadRequest, "VERIFICATION_EMAIL_NOT_ENABLED", "Verification email isn't enabled")
	ErrEmailAlreadyVerified                 = Err(http.StatusBadRequest, "EMAIL_ALREADY_VERIFIED", "Email is already verified")
	ErrEmailMismatch                        = Err(http.StatusBadRequest, "EMAIL_MISMATCH", "Email mismatch")
	ErrSessionNotFresh                      = Err(http.StatusForbidden, "SESSION_NOT_FRESH", "Session is not fresh")
	ErrLinkedAccountAlreadyExists           = Err(http.StatusBadRequest, "LINKED_ACCOUNT_ALREADY_EXISTS", "Linked account already exists")
	ErrInvalidOrigin                        = Err(http.StatusForbidden, "INVALID_ORIGIN", "Invalid origin")
	ErrInvalidCallbackURL                   = Err(http.StatusForbidden, "INVALID_CALLBACK_URL", "Invalid callbackURL")
	ErrInvalidRedirectURL                   = Err(http.StatusForbidden, "INVALID_REDIRECT_URL", "Invalid redirectURL")
	ErrInvalidErrorCallbackURL              = Err(http.StatusForbidden, "INVALID_ERROR_CALLBACK_URL", "Invalid errorCallbackURL")
	ErrInvalidNewUserCallbackURL            = Err(http.StatusForbidden, "INVALID_NEW_USER_CALLBACK_URL", "Invalid newUserCallbackURL")
	ErrMissingOrNullOrigin                  = Err(http.StatusForbidden, "MISSING_OR_NULL_ORIGIN", "Missing or null Origin")
	ErrCallbackURLRequired                  = Err(http.StatusBadRequest, "CALLBACK_URL_REQUIRED", "callbackURL is required")
	ErrFailedToCreateVerification           = Err(http.StatusInternalServerError, "FAILED_TO_CREATE_VERIFICATION", "Unable to create verification")
	ErrFieldNotAllowed                      = Err(http.StatusBadRequest, "FIELD_NOT_ALLOWED", "Field not allowed to be set")
	ErrAsyncValidationNotSupported          = Err(http.StatusInternalServerError, "ASYNC_VALIDATION_NOT_SUPPORTED", "Async validation is not supported")
	ErrValidationError                      = Err(http.StatusBadRequest, "VALIDATION_ERROR", "Validation Error")
	ErrMissingField                         = Err(http.StatusBadRequest, "MISSING_FIELD", "Field is required")
	ErrMethodNotAllowedDeferSessionRequired = Err(http.StatusMethodNotAllowed, "METHOD_NOT_ALLOWED_DEFER_SESSION_REQUIRED", "POST method requires deferSessionRefresh to be enabled in session config")
	ErrBodyMustBeAnObject                   = Err(http.StatusBadRequest, "BODY_MUST_BE_AN_OBJECT", "Body must be an object")
	ErrPasswordAlreadySet                   = Err(http.StatusBadRequest, "PASSWORD_ALREADY_SET", "User already has a password set")

	// ErrUnauthorized is thrown inline by better-auth's session middlewares, not part of BASE_ERROR_CODES.
	ErrUnauthorized = Err(http.StatusUnauthorized, "UNAUTHORIZED", "Unauthorized")
)
